language: python

python:
  - "2.7"
  - "3.5"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script: coverage run runtests.py

after_success:
  coveralls

branches:
  only:
    - develop
    - master

